path_classifiers:
  library:
    - Libraries
  test:
    - Tests
  documentation:
    - Documents

extraction:
  cpp:
    prepare:
      packages:
        - tar
        - wget
    after_prepare:
      - CMAKE_URL="https://cmake.org/files/v3.19/cmake-3.19.8-Linux-x86_64.tar.gz"
      - pushd /tmp
      - mkdir cmake && wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      - export PATH=/tmp/cmake/bin:${PATH}
      - popd
      - cmake --version
