language: cpp
os: linux
dist: focal

addons:
  sonarcloud:
    organization: "utilforever-github"
    token:
      secure: "f1puOiDV2tTq2FX2vJhQftnK9ffJ6+L7lPvEa1j1CumGG+aEbdYQxhz2o2qBJm7nzy/TbD5RW31HS/ml7n6fH6y07CMaW4P2uaOCyNRQMSMeR4V+bE64vaJQWaNecUTX2IyigjOJWJoi5nt5H2MPNTZ0ontQQpmsxwqMG/EOm4z/EK6qfkJkir+bZ80a5p3du5QQC+OI6HxYw6fGIUzB0yw+/BT9pFU4q1L4pBeVMJI0uj+Vfq9d1BnlpsUDRmZ+0rqCQzqDwd5E1G8yMqj5bfrO0l2zrkkiGDrnf8yXaZBJQBBySXkEc+4a+7ob4uzS84MxqR5lSVbUPHQQtS1YxtfF88i14ez2xsHAxejrccEHxaLUiykd5Inx91Q7FLSpvzXk31xomtYjO0wcKRGlqLQHhh0e9ppZxxs9e4vR03pdzyLiFtxoJ16tg9OC6S5PEWsJM1eDzU5EM9UFNJBtiJDAXjTFzMGuOOCEXnMvDbMuwIGNuO8FtOL0CesrTCbK6ks43p9KaETBO4zGaJSN9FCY/9zoCoaRiVqUgUUHKa+B2R+tLch1conMMmaiSEKH8aTZmg137gTM8iPLKNYBT9LX0B8QI8qxI8D+hp1K8UYPfUCkVBQcr0ZDcXmgg/kFrEA2L+sm/pe2cV24sHSK7cKcBlZELb0Whm24I0j9URI="

script:
  # Install packages
  - sudo apt-get install -yq gcovr ggcov lcov curl
  # Install a recent CMake
  # first we create a directory for the CMake binaries
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  # we use wget to fetch the cmake binaries
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.20/cmake-3.20.2-linux-x86_64.tar.gz
  # extract the binaries; the output here is quite lengthy,
  # so we swallow it to not clutter up the travis console
  - tar -xvf cmake-3.20.2-linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.20.2-linux-x86_64 cmake-install
  # add both the top-level directory and the bin directory from the archive
  # to the system PATH. By adding it to the front of the path we hide the
  # preinstalled CMake with our own.
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  # don't forget to switch back to the main build directory once you are done
  - cd ${TRAVIS_BUILD_DIR}
  # Configure build
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_COVERAGE=ON -DBUILD_SONARCLOUD=ON ..
  # Wraps the compilation with the Build Wrapper to generate configuration
  # (used later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir ../bw-output make all
  # Execute some tests
  - lcov --gcov-tool /usr/bin/gcov -c -i -d Tests/UnitTests -o base.info
  - bin/UnitTests
  - lcov --gcov-tool /usr/bin/gcov -c -d Tests/UnitTests -o test.info
  - lcov --gcov-tool /usr/bin/gcov -a base.info -a test.info -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -r coverage.info '/usr/*' -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -r coverage.info '*/Examples/*' -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -r coverage.info '*/Libraries/*' -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -r coverage.info '*/Tests/*' -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -l coverage.info
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - cd ..
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'