codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 50...100

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: true
    changes: false

# We don't want statistics for the tests themselves and certainly not for the
# benchmarks and boost libraries. Note that while we exclude the gcov data for
# these patterns in the codecov call (codecov --gcov-glob ...), the fact that
# our code references these areas also means we need to tell codecov itself to
# ignore them from the stats.
ignore:
- "Builds/**/*"
- "Documents/**/*"
- "Examples/ClaraUtils.hpp"
- "Examples/**/*"
- "Includes/API/**/*"
- "Libraries/**/*"
- "Medias/**/*"
- "Resources/**/*"
- "Scripts/**/*"
- "Sources/API/**/*"
- "Tests/ManualTests/*.hpp"
- "Tests/ManualTests/*.cpp"
- "Tests/MemPerfTests/*.hpp"
- "Tests/MemPerfTests/*.cpp"
- "Tests/PythonTests/*.py"
- "Tests/TimePerfTests/*.hpp"
- "Tests/TimePerfTests/*.cpp"

comment:
  layout: "header, diff, changes, uncovered"
  behavior: default  # update if exists else create new