name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          # Ubuntu 22.04 + gcc-13
          - name: "Ubuntu 22.04 + gcc-13"
            os: ubuntu-22.04
            compiler: gcc
            version: "13"
          # Ubuntu 22.04 + gcc-12
          - name: "Ubuntu 22.04 + gcc-12"
            os: ubuntu-22.04
            compiler: gcc
            version: "12"
          # Ubuntu 22.04 + gcc-11
          - name: "Ubuntu 22.04 + gcc-11"
            os: ubuntu-22.04
            compiler: gcc
            version: "11"
          # Ubuntu 22.04 + clang-15
          - name: "Ubuntu 22.04 + clang-15"
            os: ubuntu-22.04
            compiler: clang
            version: "15"
          # Ubuntu 22.04 + clang-14
          - name: "Ubuntu 22.04 + clang-14"
            os: ubuntu-22.04
            compiler: clang
            version: "14"
          # Ubuntu 22.04 + clang-13
          - name: "Ubuntu 22.04 + clang-13"
            os: ubuntu-22.04
            compiler: clang
            version: "13"

    runs-on: ${{ matrix.os }}
    name: 🐧 Build - ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install packages
      run: sudo apt-get install -yq python3-setuptools
    - name: Configure Compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
        else
          echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
        fi
    - name: Configure Build
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      run: cd build && make
    - name: Run Unit Test
      run: /home/runner/work/CubbyFlow/CubbyFlow/build/bin/UnitTests
    - name: Run Python Test
      run: |
        pip3 install -r requirements.txt
        pip3 install .
        python3 -m pytest Tests/PythonTests/